# Header
menu:
  首页: ./
  归档: archives
# rss: /atom.xml

#
open_graph: false

# Content
excerpt_link: Read More
fancybox: false


# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
- links

# Links
links:
  热前端: http://reqianduan.com
  西瓜宝宝主题站: http://xiguabaobao.com
  一组不错的配色flat-ui: http://flatuicolors.com/
  easy icon-这里有你需要的图标: http://www.easyicon.cn/
  西瓜宝宝主题站: http://xiguabaobao.com

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins: 
fb_app_id: